name = "http-forward"
compatibility_date = "2025-02-21"

main = "src/index.js"

workers_dev = false
preview_urls = false
minify = true
upload_source_maps = false
keep_vars = true

[dev]
ip = "0.0.0.0"
port = 8787

[vars]
SRC_REGIONS = ['CN', 'HK', 'SG']
SRC_IPV4_RANGES = []
SRC_IPV6_RANGES = []
TARGETS = ['.github.com', '.githubusercontent.com', '.gitlab.com']
